In [70]:
import pandas as pd
df = pd.read_csv("result/summary_all_strategies_feasible.csv")
df.sample(5)

,Asset,Model,Model Family,Feature Set,Input Type,Feature Type,Strategy Mode,Strategy Label,Cost Regime,Long Threshold,...,Test Recall,Test Avg Return,Cumulative Return,Maximum Drawdown,Turnover,Number of Trades,Annualized Sharpe,Model Params,Log Path,Feasibility Bucket
214,ETH,SMA,Rule,rule_based,rule,rule,short_only,short,no_cost,NaN,...,0.378455,0.000024,-0.053173,-0.370317,110.0,110.0,0.159920,"{""long_window"": 100, ""short_window"": 30}",data/trading_logs/no_cost/short_only/sma/rule_...,feasible
61,BTC,Logistic Regression,ML,ohlc_extended,ohlc,extended,long_only,long,with_cost,0.59,...,0.027883,0.000094,-0.056324,-0.155816,436.0,436.0,-0.372767,"{""model_dir"": ""models/logistic_regression/ohlc...",data/trading_logs/with_cost/long_only/logistic...,feasible
351,XRP,LightGBM,ML,candle_extended,candle,extended,long_short,long_short,with_cost,0.72,...,0.018310,0.000336,-0.046307,-0.355320,664.0,664.0,0.029452,"{""model_dir"": ""models/lightgbm/candle_extended...",data/trading_logs/with_cost/long_short/lightgb...,feasible
259,SOL,LightGBM,ML,ohlc_raw,ohlc,raw,long_only,long,with_cost,0.72,...,0.063780,-0.000578,-0.479761,-0.522765,1232.0,1232.0,-3.010837,"{""model_dir"": ""models/lightgbm/ohlc_raw/sol"", ...",data/trading_logs/with_cost/long_only/lightgbm...,feasible
289,SOL,XGBoost,ML,candle_extended,candle,extended,long_only,long,with_cost,0.72,...,0.103485,-0.000014,-0.312473,-0.389416,1746.0,1746.0,-0.882044,"{""model_dir"": ""models/xgboost/candle_extended/...",data/trading_logs/with_cost/long_only/xgboost/...,feasible

In [58]:
df = pd.read_csv("result/summary_all_strategies_feasible.csv")

# check columns
print(df.columns)

# sort by Sharpe for each asset
df = df[(df["Cost Regime"] != "no_cost") & (df["Model Family"] == "ML") & (df["Strategy Label"] == "long")]
df = df.sort_values(["Asset", "Annualized Sharpe"], ascending=[True, False])
df = df[["Asset", "Model", "Strategy Label", "Annualized Sharpe"]]
df[df["Asset"] == "BTC"]["Annualized Sharpe"].mean()
df.head()

Index(['Asset', 'Model', 'Model Family', 'Feature Set', 'Input Type',
       'Feature Type', 'Strategy Mode', 'Strategy Label', 'Cost Regime',
       'Long Threshold', 'Short Threshold', 'Threshold Feasible',
       'Validation Sharpe', 'Validation Precision', 'Validation Recall',
       'Validation Avg Return', 'Validation Trades', 'Validation Signal Ratio',
       'Test Sharpe', 'Test Precision', 'Test Recall', 'Test Avg Return',
       'Cumulative Return', 'Maximum Drawdown', 'Turnover', 'Number of Trades',
       'Annualized Sharpe', 'Model Params', 'Log Path', 'Feasibility Bucket'],
      dtype='object')

   Asset                Model Strategy Label  Annualized Sharpe
7    BTC                  GRU           long           1.067036
13   BTC                  GRU           long           0.945086
49   BTC  Logistic Regression           long           0.805053
55   BTC  Logistic Regression           long           0.261014
37   BTC             LightGBM           long           0.257446

In [93]:
df = pd.read_csv("result/summary_all_strategies_feasible.csv")
df = df[(df["Cost Regime"] == "no_cost") & (df["Model Family"] == "Rule")].sort_values(["Asset", "Annualized Sharpe"])
df["Cumulative Return"].median()

-0.0634445959203431

In [95]:
df = pd.read_csv("result/summary_all_strategies_feasible.csv")
df.groupby(["Model", "Strategy Label"])["Annualized Sharpe"].median()

Model                Strategy Label
GRU                  long              0.906430
                     long_short       -0.468625
                     short            -0.645501
LightGBM             long              0.419787
                     long_short       -0.433859
                     short            -0.774233
Logistic Regression  long              0.777295
                     long_short        0.223813
                     short            -0.262648
RSI                  long             -0.093819
                     long_short       -0.709531
                     short            -0.970828
SMA                  long              0.535365
                     long_short       -0.486338
                     short            -0.604840
XGBoost              long             -0.279875
                     long_short       -0.880565
                     short            -0.757251
Name: Annualized Sharpe, dtype: float64

In [96]:
df = pd.read_csv("result/summary_all_strategies_feasible.csv")
df.groupby(["Feature Set", "Strategy Label"])["Annualized Sharpe"].median()

Feature Set      Strategy Label
candle_extended  long              0.964788
                 long_short        0.454086
                 short            -0.655860
candle_raw       long              0.082827
                 long_short       -0.600288
                 short            -0.742192
ohlc_extended    long              0.759339
                 long_short       -0.455579
                 short            -0.619114
ohlc_raw         long              0.241647
                 long_short       -0.358219
                 short            -0.584802
rule_based       long              0.239491
                 long_short       -0.573120
                 short            -0.713653
Name: Annualized Sharpe, dtype: float64

In [102]:
df = pd.read_csv("result/summary_all_strategies_feasible.csv")
df.groupby(["Asset", "Strategy Label"])[["Number of Trades", "Turnover", "Annualized Sharpe"]].mean()

                      Number of Trades     Turnover  Annualized Sharpe
Asset Strategy Label
BTC   long                 1017.277778  1017.277778           0.239845
      long_short           2732.111111  2973.555556          -0.810191
      short                2143.000000  2142.888889          -1.027994
ETH   long                 1196.722222  1196.722222          -0.100844
      long_short           2423.055556  2547.611111          -0.549813
      short                1486.722222  1486.666667          -0.771775
SOL   long                 1439.555556  1439.555556           0.191215
      long_short           2304.944444  2492.666667          -0.041630
      short                1345.500000  1345.444444          -0.173731
XRP   long                  688.000000   688.000000           0.913504
      long_short           2275.388889  2372.777778          -0.804122
      short                1824.666667  1824.444444          -1.017307

In [109]:
df = pd.read_csv("result/summary_all_strategies_feasible.csv")
df.groupby([ "Asset", "Strategy Label"])[["Number of Trades", "Turnover", "Annualized Sharpe"]].mean()

                      Number of Trades     Turnover  Annualized Sharpe
Asset Strategy Label
BTC   long                 1017.277778  1017.277778           0.239845
      long_short           2732.111111  2973.555556          -0.810191
      short                2143.000000  2142.888889          -1.027994
ETH   long                 1196.722222  1196.722222          -0.100844
      long_short           2423.055556  2547.611111          -0.549813
      short                1486.722222  1486.666667          -0.771775
SOL   long                 1439.555556  1439.555556           0.191215
      long_short           2304.944444  2492.666667          -0.041630
      short                1345.500000  1345.444444          -0.173731
XRP   long                  688.000000   688.000000           0.913504
      long_short           2275.388889  2372.777778          -0.804122
      short                1824.666667  1824.444444          -1.017307